#!/usr/bin/env python3
"""Build explain topics from markdown resource files.

Generates:
  cognigy-vibe-mcp/cognigy_mcp/tools/_explain_topics_generated.py
  plugin/skills/explain/SKILL.md

Run with: uv run scripts/build_explain_topics.py
"""
from __future__ import annotations
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
RESOURCES = REPO_ROOT / "plugin" / "skills" / "explain" / "resources"
TEMPLATE = REPO_ROOT / "plugin" / "skills" / "explain" / "SKILL.md.template"
GENERATED_PY = REPO_ROOT / "cognigy-vibe-mcp" / "cognigy_mcp" / "tools" / "_explain_topics_generated.py"
GENERATED_SKILL = REPO_ROOT / "plugin" / "skills" / "explain" / "SKILL.md"


@dataclass
class TopicEntry:
    topic: str
    description: str
    group: str | None
    body: str


def parse_frontmatter(content: str, path: Path) -> tuple[dict[str, str], str]:
    """Parse YAML frontmatter from markdown content. Returns (metadata, body)."""
    match = re.match(r'^---\r?\n(.*?)\r?\n---\r?\n', content, re.DOTALL)
    if not match:
        raise ValueError(f"No frontmatter found in {path}")
    fm_text = match.group(1)
    body = content[match.end():]
    metadata: dict[str, str] = {}
    for line in fm_text.splitlines():
        if ':' in line:
            key, _, value = line.partition(':')
            metadata[key.strip()] = value.strip()
    return metadata, body


def scan_resources(resources_dir: Path) -> list[TopicEntry]:
    """Recursively scan resources directory and return sorted TopicEntry list."""
    entries: list[TopicEntry] = []
    for md_file in sorted(resources_dir.rglob("*.md")):
        content = md_file.read_text(encoding="utf-8")
        try:
            metadata, body = parse_frontmatter(content, md_file)
        except ValueError as e:
            print(f"ERROR: {e}", file=sys.stderr)
            sys.exit(1)
        topic = metadata.get("topic", "").strip()
        description = metadata.get("description", "").strip()
        group = metadata.get("group", "").strip() or None
        if not topic:
            print(f"ERROR: Missing 'topic' in frontmatter: {md_file}", file=sys.stderr)
            sys.exit(1)
        if not description:
            print(f"ERROR: Missing 'description' in frontmatter: {md_file}", file=sys.stderr)
            sys.exit(1)
        entries.append(TopicEntry(topic=topic, description=description, group=group, body=body.strip()))
    # Check for duplicate topic names
    seen: set[str] = set()
    for entry in entries:
        if entry.topic in seen:
            print(f"ERROR: Duplicate topic '{entry.topic}' declared in multiple files", file=sys.stderr)
            sys.exit(1)
        seen.add(entry.topic)
    # Sort: flat topics (no group) first, then grouped by group name then topic
    entries.sort(key=lambda e: (e.group is not None, e.group or "", e.topic))
    return entries


def build_topic_index(entries: list[TopicEntry]) -> str:
    """Build the _TOPIC_INDEX string with group headings."""
    lines: list[str] = ["Topics and what they cover:\n"]
    current_group: str | None = "SENTINEL"
    for entry in entries:
        if entry.group != current_group:
            current_group = entry.group
            if current_group is not None:
                lines.append(f"\n{current_group}:")
        lines.append(f"  {entry.topic:<26} {entry.description}")
    return "\n".join(lines)


def generate_python(entries: list[TopicEntry], output_path: Path) -> None:
    """Write _explain_topics_generated.py."""
    topics_repr = repr([e.topic for e in entries])
    index = build_topic_index(entries)
    content_items = "\n".join(f"    {e.topic!r}: {e.body!r}," for e in entries)
    code = f'''# AUTO-GENERATED by scripts/build_explain_topics.py — do not edit directly
# Source: plugin/skills/explain/resources/
from __future__ import annotations

TOPICS: list[str] = {topics_repr}

_TOPIC_INDEX = """
{index}
"""

_CONTENT: dict[str, str] = {{
{content_items}
}}
'''
    output_path.write_text(code, encoding="utf-8")
    print(f"Generated: {output_path.relative_to(REPO_ROOT)}")


def generate_skill_md(entries: list[TopicEntry], template_path: Path, output_path: Path) -> None:
    """Render SKILL.md.template → SKILL.md."""
    template = template_path.read_text(encoding="utf-8")
    index = build_topic_index(entries)
    output_path.write_text(template.replace("{{TOPIC_REGISTRY}}", index), encoding="utf-8")
    print(f"Generated: {output_path.relative_to(REPO_ROOT)}")


def main() -> None:
    if not RESOURCES.exists():
        print(f"ERROR: resources directory not found: {RESOURCES}", file=sys.stderr)
        sys.exit(1)
    entries = scan_resources(RESOURCES)
    if not entries:
        print("ERROR: no topic files found", file=sys.stderr)
        sys.exit(1)
    generate_python(entries, GENERATED_PY)
    generate_skill_md(entries, TEMPLATE, GENERATED_SKILL)
    print(f"Done. {len(entries)} topic(s) processed.")


if __name__ == "__main__":
    main()
